CREATE TABLE USER(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255),
  LOGIN VARCHAR(255),
  PASSWORD VARCHAR(64),
  SALT VARCHAR(64),
  CONSTRAINT UNQ_USER_LOGIN
    UNIQUE (LOGIN)
);

CREATE TABLE AUTHORITY(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT,
  ROLE VARCHAR(255),
  SITE VARCHAR(255),
  CONSTRAINT FK_AUTHORITY_USER_ID
    FOREIGN KEY (USER_ID)
    REFERENCES USER (ID)
);

CREATE TABLE ACTIVITY(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  AUTHORITY_ID INT,
  LOGIN_DATE DATE,
  LOGOUT_DATE DATE,
  VOLUME INT,
  CONSTRAINT FK_ACTIVITY_AUTHORITY_ID
    FOREIGN KEY (AUTHORITY_ID)
    REFERENCES AUTHORITY (ID)
);

CREATE INDEX IDX_AUTHORITY
  ON AUTHORITY (USER_ID, ROLE);
