CREATE TABLE AUTH(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  LOGIN VARCHAR(255),
  HASH VARCHAR(64),
  SALT VARCHAR(64),
  NAME VARCHAR(255),
  CONSTRAINT UNQ_USER_LOGIN
    UNIQUE (LOGIN)
);

CREATE TABLE ROLES(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  AUTH_ID INT,
  ROLE VARCHAR(255),
  RESOURCE VARCHAR(255),
  CONSTRAINT FK_ROLES_AUTH_ID
    FOREIGN KEY (AUTH_ID)
    REFERENCES AUTH (ID)
);

CREATE TABLE ACCOUNTING(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ROLES_ID INT,
  START_DATE DATE,
  END_DATE DATE,
  VOLUME INT,
  CONSTRAINT FK_ACCOUNTING_ROLES_ID
    FOREIGN KEY (ROLES_ID)
    REFERENCES ROLES (ID)
);

CREATE INDEX IDX_AUTHORITY
  ON ROLES (AUTH_ID, ROLE);