CREATE TABLE USER_ACCOUNT(
  ID		INT AUTO_INCREMENT PRIMARY KEY,
  NAME		VARCHAR(255),
  LOGIN		VARCHAR(255),
  PASSWORD	VARCHAR(32),
  SALT		VARCHAR(32),
  CONSTRAINT UNQ_USER_LOGIN UNIQUE (LOGIN)
);

CREATE TABLE PERMISSIONS(
  ID		INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID	INT,
  ROLE		VARCHAR(255),
  SITE		VARCHAR(255),
  CONSTRAINT FK_AUTHORITY_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT (ID)
);

CREATE TABLE ACTIVITY(
  ID			INT AUTO_INCREMENT PRIMARY KEY,
  AUTHORITY_ID	INT,
  LOGIN_DATE	DATE,
  LOGOUT_DATE	DATE,
  VOLUME		INT,
  CONSTRAINT FK_ACTIVITY_AUTHORITY_ID FOREIGN KEY (AUTHORITY_ID) REFERENCES PERMISSIONS (ID)
);

CREATE INDEX IDX_PERMISSIONS
  ON PERMISSIONS (USER_ID, ROLE);
